import ExcelJS from 'exceljs';
import type { DCFResult, LBOResult } from './valuation';
import type { FinancialData } from '../types';

// ─── Colour palette ───────────────────────────────────────────────────────────
const C = {
  headerBg:    '1F3864',   // dark navy  — section headers
  headerFg:    'FFFFFF',   // white text
  subheaderBg: '2E75B6',   // mid blue   — sub-headers
  subheaderFg: 'FFFFFF',
  inputBg:     'FFF2CC',   // amber      — assumption / input cells
  inputFg:     '000000',
  calcBg:      'FFFFFF',   // white      — calculated outputs
  totalBg:     'D6E4F0',   // light blue — subtotal / total rows
  negativeFg:  'C00000',   // red        — negative numbers
  borderColor: 'BFBFBF',
} as const;

// ─── Number formats ───────────────────────────────────────────────────────────
const FMT = {
  billions: '#,##0.0"B"',
  millions: '#,##0.0"M"',
  pct1:     '0.0%',
  pct2:     '0.00%',
  mult:     '0.0"x"',
  integer:  '#,##0',
} as const;


// ════════════════════════════════════════════════════════════════════════════════
// Public entry points
// ════════════════════════════════════════════════════════════════════════════════

/** Build a DCF workbook and return it as a Buffer for upload. */
export async function buildDCFExcel(
  financialData: FinancialData,
  result: DCFResult
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator  = 'Nexus Valuation';
  wb.created  = new Date();

  addDCFSummarySheet(wb, financialData, result);
  addDCFAssumptionsSheet(wb, result);
  addDCFModelSheet(wb, financialData, result);
  addHistoricalSheet(wb, financialData);

  return Buffer.from(await wb.xlsx.writeBuffer());
}

/** Build an LBO workbook and return it as a Buffer for upload. */
export async function buildLBOExcel(
  financialData: FinancialData,
  result: LBOResult
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator  = 'Nexus Valuation';
  wb.created  = new Date();

  addLBOSummarySheet(wb, financialData, result);
  addLBOAssumptionsSheet(wb, result);
  addLBOModelSheet(wb, financialData, result);
  addHistoricalSheet(wb, financialData);

  return Buffer.from(await wb.xlsx.writeBuffer());
}


// ════════════════════════════════════════════════════════════════════════════════
// DCF Sheets
// ════════════════════════════════════════════════════════════════════════════════

function addDCFSummarySheet(
  wb: ExcelJS.Workbook,
  fd: FinancialData,
  result: DCFResult
): void {
  const ws = wb.addWorksheet('Summary');
  ws.views = [{ state: 'frozen', ySplit: 1 }];
  setColumnWidths(ws, [30, 20, 20]);

  // Title
  mergeHeader(ws, `${fd.company.name} (${fd.company.ticker}) — DCF Valuation`, 1, 3, 1);
  mergeHeader(ws, `Generated by Nexus Valuation | ${new Date().toLocaleDateString()}`, 2, 3, 2);

  ws.addRow([]);

  // Key outputs table
  sectionHeader(ws, 'KEY OUTPUTS', 3);
  const rows: [string, number, string][] = [
    ['Enterprise Value',     result.enterpriseValue, FMT.billions],
    ['Net Debt',             result.netDebt,          FMT.billions],
    ['Equity Value',         result.equityValue,      FMT.billions],
    ['PV of Forecast FCFs',  result.years.reduce((s, y) => s + y.pvUFCF, 0), FMT.billions],
    ['PV of Terminal Value', result.pvTerminalValue,  FMT.billions],
    ['Terminal Value',       result.terminalValue,    FMT.billions],
  ];
  for (const [label, val, fmt] of rows) {
    outputRow(ws, label, val / 1e9, fmt);
  }

  ws.addRow([]);
  sectionHeader(ws, 'VALUATION BRIDGE', 3);
  outputRow(ws, 'WACC',                result.assumptions.wacc,               FMT.pct1);
  outputRow(ws, 'Terminal Growth Rate', result.assumptions.terminalGrowthRate, FMT.pct1);
  outputRow(ws, 'Forecast Years',       result.assumptions.forecastYears,      FMT.integer);

  ws.addRow([]);
  sectionHeader(ws, 'TV AS % OF TOTAL EV', 3);
  const tvPct = result.pvTerminalValue / result.enterpriseValue;
  outputRow(ws, 'Terminal Value %', tvPct, FMT.pct1);
}


function addDCFAssumptionsSheet(wb: ExcelJS.Workbook, result: DCFResult): void {
  const ws = wb.addWorksheet('Assumptions');
  setColumnWidths(ws, [35, 20]);

  mergeHeader(ws, 'DCF ASSUMPTIONS', 1, 2, 1);
  ws.addRow([]);

  sectionHeader(ws, 'DISCOUNT RATE', 2);
  inputRow(ws, 'WACC',                    result.assumptions.wacc,               FMT.pct2);
  inputRow(ws, 'Terminal Growth Rate',     result.assumptions.terminalGrowthRate, FMT.pct2);

  ws.addRow([]);
  sectionHeader(ws, 'INCOME STATEMENT', 2);
  inputRow(ws, 'EBITDA Margin',           result.assumptions.ebitdaMargin,            FMT.pct1);
  inputRow(ws, 'Tax Rate',                result.assumptions.taxRate,                 FMT.pct1);

  ws.addRow([]);
  sectionHeader(ws, 'CAPITAL STRUCTURE', 2);
  inputRow(ws, 'CapEx as % of Revenue',   result.assumptions.capexAsPercentOfRevenue, FMT.pct1);
  inputRow(ws, 'NWC as % of Revenue',     result.assumptions.nwcAsPercentOfRevenue,   FMT.pct1);

  ws.addRow([]);
  sectionHeader(ws, 'REVENUE GROWTH', 2);
  result.assumptions.revenueGrowthRates.forEach((r, i) => {
    inputRow(ws, `Year ${i + 1} Growth`, r, FMT.pct1);
  });
}


function addDCFModelSheet(
  wb: ExcelJS.Workbook,
  fd: FinancialData,
  result: DCFResult
): void {
  const ws = wb.addWorksheet('DCF Model');
  ws.views = [{ state: 'frozen', xSplit: 1, ySplit: 3 }];

  const yearLabels = result.years.map(y => `Year ${y.year}`);
  setColumnWidths(ws, [32, ...yearLabels.map(() => 16)]);

  // ── Headers ──────────────────────────────────────────────
  const titleRow = ws.addRow(['DCF MODEL — UNLEVERED FREE CASH FLOW', ...yearLabels]);
  styleRow(titleRow, C.headerBg, C.headerFg, true);

  const baseRow = ws.addRow(['Base Revenue', result.baseRevenue / 1e9]);
  styleRow(baseRow, C.subheaderBg, C.subheaderFg, false);
  baseRow.getCell(2).numFmt = FMT.billions;
  ws.addRow([]);

  // ── Income section ────────────────────────────────────────
  modelSectionHeader(ws, 'INCOME STATEMENT', yearLabels.length);

  modelRow(ws, 'Revenue',               result.years.map(y => y.revenue   / 1e9), FMT.billions, false);
  modelRow(ws, 'EBITDA',                result.years.map(y => y.ebitda    / 1e9), FMT.billions, false);
  modelRow(ws, '  D&A',                 result.years.map(y => -y.da       / 1e9), FMT.billions, false);
  modelRow(ws, 'EBIT',                  result.years.map(y => y.ebit      / 1e9), FMT.billions, true);
  modelRow(ws, 'NOPAT (EBIT × (1-t))', result.years.map(y => y.nopat     / 1e9), FMT.billions, true);

  ws.addRow([]);
  modelSectionHeader(ws, 'FREE CASH FLOW BRIDGE', yearLabels.length);
  modelRow(ws, 'NOPAT',              result.years.map(y =>  y.nopat     / 1e9), FMT.billions, false);
  modelRow(ws, '  + D&A',           result.years.map(y =>  y.da        / 1e9), FMT.billions, false);
  modelRow(ws, '  - CapEx',         result.years.map(y => -y.capex     / 1e9), FMT.billions, false);
  modelRow(ws, '  - ΔNWC',          result.years.map(y => -y.changeInNWC / 1e9), FMT.billions, false);
  modelRow(ws, 'Unlevered FCF',     result.years.map(y =>  y.ufcf      / 1e9), FMT.billions, true);

  ws.addRow([]);
  modelSectionHeader(ws, 'DISCOUNTING', yearLabels.length);
  modelRow(ws, 'Discount Factor',   result.years.map(y => y.discountFactor), FMT.pct2, false);
  modelRow(ws, 'PV of UFCF',       result.years.map(y => y.pvUFCF    / 1e9), FMT.billions, true);

  ws.addRow([]);
  modelSectionHeader(ws, 'VALUATION SUMMARY', yearLabels.length);

  const summaryItems: [string, number][] = [
    ['Sum of PV(FCFs)',     result.years.reduce((s, y) => s + y.pvUFCF, 0) / 1e9],
    ['PV of Terminal Value', result.pvTerminalValue / 1e9],
    ['Enterprise Value',    result.enterpriseValue  / 1e9],
    ['Less: Net Debt',     -result.netDebt          / 1e9],
    ['Equity Value',        result.equityValue      / 1e9],
  ];
  for (const [label, val] of summaryItems) {
    const r = ws.addRow([label, val]);
    r.getCell(1).font = { bold: label === 'Equity Value' || label === 'Enterprise Value' };
    r.getCell(2).numFmt = FMT.billions;
    r.getCell(2).font = { bold: label === 'Equity Value' || label === 'Enterprise Value' };
    if (label === 'Equity Value') fillRow(r, C.totalBg, 2);
    applyBorders(r, 2);
  }
}


// ════════════════════════════════════════════════════════════════════════════════
// LBO Sheets
// ════════════════════════════════════════════════════════════════════════════════

function addLBOSummarySheet(
  wb: ExcelJS.Workbook,
  fd: FinancialData,
  result: LBOResult
): void {
  const ws = wb.addWorksheet('Summary');
  setColumnWidths(ws, [30, 20, 20]);

  mergeHeader(ws, `${fd.company.name} (${fd.company.ticker}) — LBO Analysis`, 1, 3, 1);
  mergeHeader(ws, `Generated by Nexus Valuation | ${new Date().toLocaleDateString()}`, 2, 3, 2);
  ws.addRow([]);

  sectionHeader(ws, 'RETURNS SUMMARY', 3);
  outputRow(ws, 'MOIC',                  result.moic,                 FMT.mult);
  outputRow(ws, 'IRR',                   result.irr,                  FMT.pct1);
  outputRow(ws, 'Holding Period (years)', result.assumptions.holdingPeriodYears, FMT.integer);

  ws.addRow([]);
  sectionHeader(ws, 'ENTRY', 3);
  outputRow(ws, 'Entry EBITDA Multiple', result.assumptions.entryEbitdaMultiple, FMT.mult);
  outputRow(ws, 'Entry Equity',          result.entryEquity / 1e9,    FMT.billions);
  outputRow(ws, 'Entry Debt',            result.entryDebt   / 1e9,    FMT.billions);
  outputRow(ws, 'Debt / EBITDA',         result.assumptions.debtToEbitda, FMT.mult);

  ws.addRow([]);
  sectionHeader(ws, 'EXIT', 3);
  outputRow(ws, 'Exit EBITDA Multiple',  result.assumptions.exitEbitdaMultiple,  FMT.mult);
  outputRow(ws, 'Exit EBITDA',           result.exitEBITDA         / 1e9, FMT.billions);
  outputRow(ws, 'Exit Enterprise Value', result.exitEnterpriseValue / 1e9, FMT.billions);
  outputRow(ws, 'Exit Debt',             result.exitDebt            / 1e9, FMT.billions);
  outputRow(ws, 'Exit Equity',           result.exitEquity          / 1e9, FMT.billions);
}


function addLBOAssumptionsSheet(wb: ExcelJS.Workbook, result: LBOResult): void {
  const ws = wb.addWorksheet('Assumptions');
  setColumnWidths(ws, [35, 20]);

  mergeHeader(ws, 'LBO ASSUMPTIONS', 1, 2, 1);
  ws.addRow([]);

  sectionHeader(ws, 'DEAL STRUCTURE', 2);
  inputRow(ws, 'Entry EBITDA Multiple',   result.assumptions.entryEbitdaMultiple,  FMT.mult);
  inputRow(ws, 'Exit EBITDA Multiple',    result.assumptions.exitEbitdaMultiple,   FMT.mult);
  inputRow(ws, 'Holding Period (years)',  result.assumptions.holdingPeriodYears,   FMT.integer);
  inputRow(ws, 'Debt / EBITDA at Entry', result.assumptions.debtToEbitda,         FMT.mult);
  inputRow(ws, 'Interest Rate on Debt',  result.assumptions.interestRate,         FMT.pct2);

  ws.addRow([]);
  sectionHeader(ws, 'OPERATING ASSUMPTIONS', 2);
  inputRow(ws, 'EBITDA Margin',           result.assumptions.ebitdaMargin,            FMT.pct1);
  inputRow(ws, 'Tax Rate',                result.assumptions.taxRate,                 FMT.pct1);
  inputRow(ws, 'CapEx as % of Revenue',   result.assumptions.capexAsPercentOfRevenue, FMT.pct1);

  ws.addRow([]);
  sectionHeader(ws, 'REVENUE GROWTH', 2);
  result.assumptions.revenueGrowthRates.forEach((r, i) => {
    inputRow(ws, `Year ${i + 1} Growth`, r, FMT.pct1);
  });
}


function addLBOModelSheet(
  wb: ExcelJS.Workbook,
  fd: FinancialData,
  result: LBOResult
): void {
  const ws = wb.addWorksheet('LBO Model');
  ws.views = [{ state: 'frozen', xSplit: 1, ySplit: 2 }];

  const yearLabels = result.years.map(y => `Year ${y.year}`);
  setColumnWidths(ws, [32, ...yearLabels.map(() => 16)]);

  const titleRow = ws.addRow(['LBO MODEL', ...yearLabels]);
  styleRow(titleRow, C.headerBg, C.headerFg, true);
  ws.addRow([]);

  modelSectionHeader(ws, 'INCOME STATEMENT', yearLabels.length);
  modelRow(ws, 'Revenue',           result.years.map(y =>  y.revenue           / 1e9), FMT.billions, false);
  modelRow(ws, 'EBITDA',            result.years.map(y =>  y.ebitda            / 1e9), FMT.billions, false);
  modelRow(ws, 'EBIT',              result.years.map(y =>  y.ebit              / 1e9), FMT.billions, false);
  modelRow(ws, '  Interest Expense',result.years.map(y => -y.interestExpense   / 1e9), FMT.billions, false);
  modelRow(ws, 'EBT',               result.years.map(y =>  y.ebt              / 1e9), FMT.billions, false);
  modelRow(ws, '  Taxes',           result.years.map(y => -y.taxes             / 1e9), FMT.billions, false);
  modelRow(ws, 'Net Income',        result.years.map(y =>  y.netIncome         / 1e9), FMT.billions, true);

  ws.addRow([]);
  modelSectionHeader(ws, 'DEBT SCHEDULE', yearLabels.length);
  modelRow(ws, 'Free Cash Flow',    result.years.map(y =>  y.freeCashFlow      / 1e9), FMT.billions, false);
  modelRow(ws, 'Debt Repaid',       result.years.map(y =>  y.debtRepaid        / 1e9), FMT.billions, false);
  modelRow(ws, 'Ending Debt',       result.years.map(y =>  y.endingDebt        / 1e9), FMT.billions, true);

  ws.addRow([]);
  modelSectionHeader(ws, 'RETURNS', yearLabels.length);

  const returnsData: [string, number][] = [
    ['Entry Equity',           result.entryEquity          / 1e9],
    ['Exit EBITDA',            result.exitEBITDA            / 1e9],
    ['Exit Enterprise Value',  result.exitEnterpriseValue  / 1e9],
    ['Exit Debt',              result.exitDebt              / 1e9],
    ['Exit Equity',            result.exitEquity            / 1e9],
    ['MOIC',                   result.moic],
    ['IRR',                    result.irr],
  ];

  for (const [label, val] of returnsData) {
    const fmt = label === 'MOIC' ? FMT.mult : label === 'IRR' ? FMT.pct1 : FMT.billions;
    const r = ws.addRow([label, val]);
    r.getCell(1).font = { bold: label === 'MOIC' || label === 'IRR' };
    r.getCell(2).numFmt = fmt;
    r.getCell(2).font  = { bold: label === 'MOIC' || label === 'IRR' };
    if (label === 'MOIC' || label === 'IRR') fillRow(r, C.totalBg, 2);
    applyBorders(r, 2);
  }
}


// ════════════════════════════════════════════════════════════════════════════════
// Shared: Historical Financials Sheet
// ════════════════════════════════════════════════════════════════════════════════

function addHistoricalSheet(wb: ExcelJS.Workbook, fd: FinancialData): void {
  const ws = wb.addWorksheet('Historical Data');

  const years = fd.incomeStatements.map(s => String(s.year));
  setColumnWidths(ws, [32, ...years.map(() => 16)]);

  const title = ws.addRow(['HISTORICAL FINANCIALS (SEC EDGAR)', ...years]);
  styleRow(title, C.headerBg, C.headerFg, true);
  ws.addRow([]);

  modelSectionHeader(ws, 'INCOME STATEMENT', years.length);
  modelRow(ws, 'Revenue',           fd.incomeStatements.map(s => s.revenue            / 1e9), FMT.billions, false);
  modelRow(ws, 'Gross Profit',      fd.incomeStatements.map(s => s.grossProfit        / 1e9), FMT.billions, false);
  modelRow(ws, 'EBITDA',            fd.incomeStatements.map(s => s.ebitda             / 1e9), FMT.billions, false);
  modelRow(ws, 'EBIT',              fd.incomeStatements.map(s => s.ebit               / 1e9), FMT.billions, false);
  modelRow(ws, 'Net Income',        fd.incomeStatements.map(s => s.netIncome          / 1e9), FMT.billions, true);

  ws.addRow([]);
  modelSectionHeader(ws, 'MARGINS', years.length);
  modelRow(ws, 'EBITDA Margin', fd.incomeStatements.map(s =>
    s.revenue > 0 ? s.ebitda / s.revenue : 0), FMT.pct1, false);
  modelRow(ws, 'Net Margin',    fd.incomeStatements.map(s =>
    s.revenue > 0 ? s.netIncome / s.revenue : 0), FMT.pct1, false);

  ws.addRow([]);
  modelSectionHeader(ws, 'CASH FLOW', years.length);
  modelRow(ws, 'Operating CF',       fd.cashFlows.map(c => c.operatingCashFlow   / 1e9), FMT.billions, false);
  modelRow(ws, 'CapEx',              fd.cashFlows.map(c => -c.capitalExpenditures / 1e9), FMT.billions, false);
  modelRow(ws, 'Free Cash Flow',     fd.cashFlows.map(c => c.freeCashFlow        / 1e9), FMT.billions, true);

  ws.addRow([]);
  modelSectionHeader(ws, 'BALANCE SHEET', years.length);
  modelRow(ws, 'Total Assets',    fd.balanceSheets.map(b => b.totalAssets  / 1e9), FMT.billions, false);
  modelRow(ws, 'Total Debt',      fd.balanceSheets.map(b => b.totalDebt    / 1e9), FMT.billions, false);
  modelRow(ws, 'Cash',            fd.balanceSheets.map(b => b.cash         / 1e9), FMT.billions, false);
  modelRow(ws, 'Total Equity',    fd.balanceSheets.map(b => b.totalEquity  / 1e9), FMT.billions, true);
}


// ════════════════════════════════════════════════════════════════════════════════
// Style helpers — keep all styling logic here so the sheet builders stay clean
// ════════════════════════════════════════════════════════════════════════════════

function setColumnWidths(ws: ExcelJS.Worksheet, widths: number[]): void {
  widths.forEach((w, i) => {
    ws.getColumn(i + 1).width = w;
  });
}

function styleRow(
  row: ExcelJS.Row,
  bgColor: string,
  fgColor: string,
  bold: boolean
): void {
  row.eachCell(cell => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF' + bgColor } };
    cell.font = { color: { argb: 'FF' + fgColor }, bold };
    cell.alignment = { vertical: 'middle', horizontal: 'center' };
  });
  row.height = 20;
}

function fillRow(row: ExcelJS.Row, bgColor: string, upToCol: number): void {
  for (let c = 1; c <= upToCol; c++) {
    row.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF' + bgColor } };
  }
}

function applyBorders(row: ExcelJS.Row, upToCol: number): void {
  const border: ExcelJS.Border = { style: 'thin', color: { argb: 'FF' + C.borderColor } };
  for (let c = 1; c <= upToCol; c++) {
    row.getCell(c).border = { top: border, bottom: border, left: border, right: border };
  }
}

/** Full-width section title bar */
function mergeHeader(
  ws: ExcelJS.Worksheet,
  text: string,
  startCol: number,
  endCol: number,
  rowNum: number
): void {
  const row = ws.getRow(rowNum);
  row.getCell(startCol).value = text;
  row.getCell(startCol).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF' + C.headerBg } };
  row.getCell(startCol).font = { color: { argb: 'FF' + C.headerFg }, bold: true, size: 13 };
  row.getCell(startCol).alignment = { vertical: 'middle', horizontal: 'left' };
  ws.mergeCells(rowNum, startCol, rowNum, endCol);
  row.height = 28;
}

/** Dark blue section header spanning the label column only */
function sectionHeader(ws: ExcelJS.Worksheet, text: string, cols: number): void {
  const row = ws.addRow([text]);
  styleRow(row, C.subheaderBg, C.subheaderFg, true);
  // Extend fill across all columns
  for (let c = 2; c <= cols; c++) {
    row.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF' + C.subheaderBg } };
  }
  row.height = 18;
}

/** Amber input cell row (2-column: label | value) */
function inputRow(ws: ExcelJS.Worksheet, label: string, value: number, fmt: string): void {
  const row = ws.addRow([label, value]);
  row.getCell(1).font = { bold: false };
  row.getCell(2).numFmt = fmt;
  row.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF' + C.inputBg } };
  row.getCell(2).alignment = { horizontal: 'right' };
  applyBorders(row, 2);
}

/** White output cell row (2-column) */
function outputRow(ws: ExcelJS.Worksheet, label: string, value: number, fmt: string): void {
  const row = ws.addRow([label, value]);
  row.getCell(2).numFmt = fmt;
  row.getCell(2).alignment = { horizontal: 'right' };
  applyBorders(row, 2);
}

/** Section header row spanning the model table width */
function modelSectionHeader(ws: ExcelJS.Worksheet, text: string, yearCount: number): void {
  const row = ws.addRow([text, ...Array(yearCount).fill(null)]);
  styleRow(row, C.subheaderBg, C.subheaderFg, true);
  row.height = 18;
}

/** A data row in the model table: label + one value per year */
function modelRow(
  ws: ExcelJS.Worksheet,
  label: string,
  values: number[],
  fmt: string,
  isTotal: boolean
): void {
  const row = ws.addRow([label, ...values]);
  row.getCell(1).font = { bold: isTotal, italic: label.startsWith('  ') };

  for (let c = 2; c <= values.length + 1; c++) {
    const cell = row.getCell(c);
    cell.numFmt = fmt;
    cell.alignment = { horizontal: 'right' };
    if (isTotal) {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF' + C.totalBg } };
      cell.font = { bold: true };
    }
    // Red font for negative values
    if (typeof cell.value === 'number' && cell.value < 0) {
      cell.font = { ...cell.font, color: { argb: 'FF' + C.negativeFg } };
    }
    const border: ExcelJS.Border = { style: 'thin', color: { argb: 'FF' + C.borderColor } };
    cell.border = { top: border, bottom: border, left: border, right: border };
  }
  const labelBorder: ExcelJS.Border = { style: 'thin', color: { argb: 'FF' + C.borderColor } };
  row.getCell(1).border = { top: labelBorder, bottom: labelBorder, left: labelBorder, right: labelBorder };
}
